# 边栏菜单
menu:
  主页: /
  标签: /tags/
  关于: /about/

# 头像
avatar:

# 社交链接
social_links:

# 图标
icon: /favicon.ico

# KaTeX 版本
katex:

# 评论代码，`MONOPAGEID` 会被自动替换为页面 ID
comment:

# 版权
copyright:
